### ISSUE TITLE
Why are the dsc values in your paper for unimatch lower than those reported in the original Unimatch article? 

### ISSUE THREAD

**Issue by Carmen279252** [AiEson/CrossMatch#4]
Thank you very much for your excellent work, but I noticed that the treatment of the ACDC dataset in your work is consistent with the original Unimatch article, and the section on preserving the optimal model after calculating dice is also consistent. However, your paper reproduces the 10% labeled Unimatch's dice value of 88.08, which was 89.9 in the original Unimatch paper, and I noticed that you implemented test.py, and I'd like to confirm that you are re-running test.py to calculate dice（88.08 ） after saving the optimal model in train_cross_match.py, Jaccard, etc. Thanks！

**Comment by AiEson** [comment]
Thanks for your attention to this work! To stay consistent with LA, [we used `latest.pth` instead of `best.pth`](https://github.com/AiEson/CrossMatch/blob/5e188cb4e2ac4d12e694d9b05cbc6624f99b74ce/ACDC/test.py#L87) to get the results in the paper. We haven't modified the main code of UniMatch, so feel free to use the implementation from the official [UniMatch repository](https://github.com/LiheYoung/UniMatch/blob/main/more-scenarios/medical/unimatch.py) in our repo to try and reproduce the results.

**Comment by Carmen279252** [comment]
> Thanks for your attention to this work! To stay consistent with LA, [we used `latest.pth` instead of `best.pth`](https://github.com/AiEson/CrossMatch/blob/5e188cb4e2ac4d12e694d9b05cbc6624f99b74ce/ACDC/test.py#L87) to get the results in the paper. We haven't modified the main code of UniMatch, so feel free to use the implementation from the official [UniMatch repository](https://github.com/LiheYoung/UniMatch/blob/main/more-scenarios/medical/unimatch.py) in our repo to try and reproduce the results.

Thank you very much for your reply, I have one more question about the dice of latest.pth did you use the results of train_cross_match.py or test.py, I noticed that the number of test images used in both are different.

**Comment by Carmen279252** [comment]
> > > Thanks for your attention to this work! To stay consistent with LA, [we used `latest.pth` instead of `best.pth`](https://github.com/AiEson/CrossMatch/blob/5e188cb4e2ac4d12e694d9b05cbc6624f99b74ce/ACDC/test.py#L87) to get the results in the paper. We haven't modified the main code of UniMatch, so feel free to use the implementation from the official [UniMatch repository](https://github.com/LiheYoung/UniMatch/blob/main/more-scenarios/medical/unimatch.py) in our repo to try and reproduce the results.
> > 
> > 
> > Thank you very much for your reply, I have one more question about the dice of latest.pth did you use the results of train_cross_match.py or test.py, I noticed that the number of test images used in both are different.
> 
> I'm using the results obtained from `test.py`. The `train_cross_match.py` only calculated DSC and did not compute 95HD and ASD. The way DSC is calculated in the two files is different. ACDC is trained in 2D and predicted in 3D. `train_cross_match.py` only calculates DSC in 2D slices.

I see. Thank you very much for your reply. Wish you success in your scientific research!
